### ISSUE TITLE
[Bug] Unballing in regen pod

### ISSUE THREAD

**Issue by Fordi** [grillstern/Laniakea#13]
Minor one: if you're in the regen pod, you can enter the "ball" state, but you can't exit it.

Recommendation: regen pod starts an animation sequence, locking the player into it until regen is complete; if player doesn't need regen, event is cancelled.  Otherwise, it's just another piece of stage without special handling.

**Comment by grillstern** [comment]
Fixed for 0.0.5. "Locked Regen Event" will def. be implemented later on.

**Comment by grillstern** [comment]
RS will be activated while Player is in Station and presses the "Special" button. 
Want to give the player a choice if he wants to use the station or not, even if HP oder EC are not maxed.
