### ISSUE TITLE
[Bug] Ball logic while not a ball

### ISSUE THREAD

**Issue by Fordi** [grillstern/Laniakea#2]
Steps to reproduce:

1.  Hold up and tap down twice.  Your feet will start to glow.  
2. Still holding up, press fire: you'll emit bombs from your gun, which then fall. 

If done quickly during a non-rolling jump while crouched against a wall, you can ball-wall-jump until you contact the ground again.

**Comment by Fordi** [comment]
Can still get into pseudo-ball mode by holding up and tapping down twice.

**Comment by grillstern** [comment]
Fixed for 0.0.6
