### ISSUE TITLE
[Wiki request] How do you pronounce "Laniakea"?

### ISSUE THREAD

**Issue by Fordi** [grillstern/Laniakea#8]
I keep waffling between "lan-ee-ack-ee-ah" and "Lah-nee-uh-kea".  Probably both are wrong.  Having recently learned "Gerudo" is pronounced with a hard G, I'd like to get this down.

**Comment by grillstern** [comment]
https://www.quora.com/How-do-you-pronounce-the-Hawaiian-word-Laniakea
