### ISSUE TITLE
[Bug] Ball physics while holding gun out

### ISSUE THREAD

**Issue by Fordi** [grillstern/Laniakea#9]
1. Press and hold "Fire"
2. Tap "down" twice - you will get glowing feet
3. Quickly release and hold "fire" again.  If holding "aim-up", you will stay standing.  If not, you'll revert to crouching.  Either way, you'll drop a bomb from your gun.
4. You can move in this state, and pass through narrow doors.

Trick can be used to drop bombs from a higher position than you should, and you can drop them inside of walls this way.

**Comment by grillstern** [comment]
Fixed the "simulate to be a ball" bug while standing. You can now enter ball state only if Fire is not hold.

**Comment by Fordi** [comment]
In my other ball-physics comment, you say check back in 0.0.5, so I'll do that here.

I'll add, using the up+down trick, you can enter the "ballish" state.  If you then press and hold "fire", you'll remain there.  So it'd probably be good to add "Up" to the buttons excluded from entering the ball state, which would fix the other ticket as well.
